# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    # config.vm.define "ansible-u-2204", autostart: false do |ansible_u_2204|
    config.vm.define "ansible-u-2204" do |ansible_u_2204|
      ansible_u_2204.vm.hostname = "ansible-u-2204"
      ansible_u_2204.vm.box = "ubuntu/jammy64"
      ansible_u_2204.vm.box_check_update = false
      ansible_u_2204.vm.synced_folder ".", "/vagrant", disabled: true
      ansible_u_2204.vm.network "private_network", ip: "10.10.10.60"
      # ansible_u_2204.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "192.168.255.151"
      # ansible_u_2204.vm.network "forwarded_port", guest: 80, host: 80
      # ansible_u_2204.vm.network "forwarded_port", guest: 9001, host: 9001
      # ansible_u_2204.ssh.host = 'localhost'
      # ansible_u_2204.vm.boot_timeout = 1800

      ansible_u_2204.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # bug feezes 'SSH auth method: private key'
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # bug feezes 'SSH auth method: private key'
        # vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        vb.name = "v_ansible-u-2204"
        vb.cpus = 3
        vb.memory = "2000"
      end
    end

    # config.vm.define "ansible-u-2004", autostart: false do |ansible_u_2004|
    config.vm.define "ansible-u-2004" do |ansible_u_2004|
      ansible_u_2004.vm.hostname = "ansible-u-2004"
      ansible_u_2004.vm.box = "ubuntu/focal64"
      ansible_u_2004.vm.box_check_update = false
      ansible_u_2004.vm.synced_folder ".", "/vagrant", disabled: true
      ansible_u_2004.vm.network "private_network", ip: "10.10.10.61"
      # ansible_u_2004.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "192.168.255.151"
      # ansible_u_2004.vm.network "forwarded_port", guest: 80, host: 80
      # ansible_u_2004.vm.network "forwarded_port", guest: 9001, host: 9001
      # ansible_u_2004.ssh.host = 'localhost'
      # ansible_u_2004.vm.boot_timeout = 1800

      ansible_u_2004.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # bug feezes 'SSH auth method: private key'
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # bug feezes 'SSH auth method: private key'
        # vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        vb.name = "v_ansible-u-2004"
        vb.cpus = 3
        vb.memory = "2000"
      end
    end

    # config.vm.define "ansible-u-1804", autostart: false do |ansible_u_1804|
    config.vm.define "ansible-u-1804" do |ansible_u_1804|
      ansible_u_1804.vm.hostname = "ansible-u-1804"
      ansible_u_1804.vm.box = "ubuntu/bionic64"
      ansible_u_1804.vm.box_check_update = false
      ansible_u_1804.vm.synced_folder ".", "/vagrant", disabled: true
      ansible_u_1804.vm.network "private_network", ip: "10.10.10.62"
      # ansible_u_1804.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "192.168.255.151"
      # ansible_u_1804.vm.network "forwarded_port", guest: 80, host: 80
      # ansible_u_1804.vm.network "forwarded_port", guest: 9001, host: 9001
      # ansible_u_1804.ssh.host = 'localhost'
      # ansible_u_1804.vm.boot_timeout = 1800

      ansible_u_1804.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # bug feezes 'SSH auth method: private key'
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # bug feezes 'SSH auth method: private key'
        # vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        vb.name = "v_ansible-u-1804"
        vb.cpus = 3
        vb.memory = "2000"
      end
    end

    # config.vm.define "ansible-d-11", autostart: false do |ansible_d_11|
    config.vm.define "ansible-d-11" do |ansible_d_11|
      ansible_d_11.vm.hostname = "ansible-d-11"
      ansible_d_11.vm.box = "debian/bullseye64"
      ansible_d_11.vm.box_check_update = false
      ansible_d_11.vm.synced_folder ".", "/vagrant", disabled: true
      ansible_d_11.vm.network "private_network", ip: "10.10.10.63"
      # ansible_d_11.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "192.168.255.151"
      # ansible_d_11.vm.network "forwarded_port", guest: 80, host: 80
      # ansible_d_11.vm.network "forwarded_port", guest: 9001, host: 9001
      # ansible_d_11.ssh.host = 'localhost'
      # ansible_d_11.vm.boot_timeout = 1800

      ansible_d_11.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # bug feezes 'SSH auth method: private key'
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # bug feezes 'SSH auth method: private key'
        # vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        vb.name = "v_ansible-d-11"
        vb.cpus = 3
        vb.memory = "2000"
      end
    end

    # config.vm.define "ansible-d-10", autostart: false do |ansible_d_10|
    config.vm.define "ansible-d-10" do |ansible_d_10|
      ansible_d_10.vm.hostname = "ansible-d-10"
      ansible_d_10.vm.box = "debian/buster64"
      ansible_d_10.vm.box_check_update = false
      ansible_d_10.vm.synced_folder ".", "/vagrant", disabled: true
      ansible_d_10.vm.network "private_network", ip: "10.10.10.64"
      # ansible_d_10.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "192.168.255.151"
      # ansible_d_10.vm.network "forwarded_port", guest: 80, host: 80
      # ansible_d_10.vm.network "forwarded_port", guest: 9001, host: 9001
      # ansible_d_10.ssh.host = 'localhost'
      # ansible_d_10.vm.boot_timeout = 1800

      ansible_d_10.vm.provider "virtualbox" do |vb|
        # vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"] # bug feezes 'SSH auth method: private key'
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL] # bug feezes 'SSH auth method: private key'
        # vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        vb.name = "v_ansible-d-10"
        vb.cpus = 3
        vb.memory = "2000"
      end
    end

    # insert ssh key
    config.vm.provision "shell" do |s|
      ssh_pub_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDH3Ze5tF0QNs+OyOq2mow53F4SPymtm4WppO47h3FL3l/Pjcge5CF28I2ulhEQLvGHhX5b2LnSyTTyWSfC1ifrAXs+5KZEzeZYgghdF6sq4Gd/bTU89ftZUD57Q7nzgA0UbmRuZHYKTyNBF+W1lXfTwZzaOJPkj5WVxaVLi1aCjqpIstVq4xMdDJj1Zr72jNpOF0PCwiL7YK2yzBrow/QMqXC9rqmlrT4b6tTDLbzwW8KQH3Jw5otrVQVSCgU+l+lVcXwnIhp14ff90kr942mx346du5rtgR5oD24EBiKcC1/szEGgUy9o4C6PkOZ60nv6gXN/iXnmgYq+fa0iSry2POVEgRK9cABP0d3wZGzyNg9IXBlRdLo0ny0vfMPxiLVdljv5yAw2YAk4rUZdY/Il0O1FOj7Z7snp3+1ugVd72EPBs9Cmr6RdLKTuNJNAU2Lvj8AZKwiuIsYGur26+pMlPqQd50yKoAbEUzhzNTibhzQ5bMbAEe/811Il+U3okvTIRgPVu5Ga6cTv0OAOw3Jx1fS4u+q2I+F+PtsIca0PG3oIhLI46CrybnilErVV2Atzbm1IGSOgWac6X7oem0MSVakl+zdOr8p5H1QioZrF9RGQH4rRml5PsrCOk+znwa9mq4T1Pv+pZbx2Lxd5Nmekdw7TeXcX3A2yB0XIWlnPEw== overdese@gmail.com"
      s.inline = <<-SHELL
        mkdir -p /home/vagrant/.ssh/ /root/.ssh/
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

  end
